import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AppLayout from '@/components/AppLayout';
import AuthProvider from '@/components/AuthProvider';
import './globals.css';
import Providers from '@/components/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Giorgi Paichadze',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AuthProvider>
            <AppLayout>{children}</AppLayout>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
